plugins:
  resolvers:
    - https://github.com/{{index GroupParts 1}}/{{index GroupParts 2}}/releases/download/v{{Version}}/{{Product}}-{{Version}}-{{OS}}-{{Arch}}.tgz
  plugins:
    - locator:
        id: com.palantir.godel-mod-plugin:mod-plugin:1.45.0
        checksums:
          darwin-amd64: 86c00f02a2fa80a2223d492e931c4ec3312b3e0c895822c2f5ed8c0ea7b2e1b9
          linux-amd64: ac50a961c95657a92105c417671b8d18dfe45da0019e72cdac0b9f5938f2ea4c
    - locator:
        id: com.palantir.godel-refreshables-plugin:refreshables-plugin:0.240.0
        checksums:
          darwin-amd64: cfda85d4b402c0e692367f2099561a2619d3a1709aab386a9d5193ca217364bd
          linux-amd64: c8b6470464653a9c89714ef160c3d2246d7bc5b809650b0331c96151dbe0608e
environment:
  GO111MODULE: "on"
  GOFLAGS: "-mod=vendor"
exclude:
  names:
    - \..+
    - vendor
    - zz_generated_refreshables.go
  paths:
    - godel
