plugins:
  resolvers:
    - https://github.com/{{index GroupParts 1}}/{{index GroupParts 2}}/releases/download/v{{Version}}/{{Product}}-{{Version}}-{{OS}}-{{Arch}}.tgz
  plugins:
    - locator:
        id: com.palantir.godel-mod-plugin:mod-plugin:1.45.0
        checksums:
          darwin-amd64: 86c00f02a2fa80a2223d492e931c4ec3312b3e0c895822c2f5ed8c0ea7b2e1b9
          linux-amd64: ac50a961c95657a92105c417671b8d18dfe45da0019e72cdac0b9f5938f2ea4c
    - locator:
        id: com.palantir.godel-refreshables-plugin:refreshables-plugin:0.235.0
        checksums:
          darwin-amd64: feef4a6639bbf253e128192e4d93737ad6f1027603d367c7b8766021958e105d
          linux-amd64: e54eb41b16b49964e95d629eb7c94a22620f3510e1cbda9f0b50a53b2a03a9b6
environment:
  GO111MODULE: "on"
  GOFLAGS: "-mod=vendor"
exclude:
  names:
    - \..+
    - vendor
    - zz_generated_refreshables.go
  paths:
    - godel
